#!/usr/bin/env zsh

set -e
#
# Set XDG Config Home
config_dir="$HOME/.config"
[[ -d $config_dir ]] || mkdir $config_dir
[[ -d $config_dir ]] && export XDG_CONFIG_HOME="$config_dir"

echo $XDG_CONFIG_HOME

function lnDot()
{
  dotName=.$1
    backup=$dotName.backup
    echo $dotName $backup $repoDir/$1

    [[ -f $dotName ]] && mv $dotName $backup

    ln -s $repoDir/$1 $dotName
}

repoDir=$(pwd)

cd $HOME

lnDot 'aliases.zsh'
lnDot 'spacemacs'
lnDot 'zprofile'
lnDot 'zshenv'
lnDot 'zshrc'

nvimConifig=$XDG_CONFIG_HOME/nvim
nvimBackup=$nvimConifig.backup
if [[ -d $nvimConifig ]]; then
    echo "Nvim config found: $nvimConifig"
    echo "Moving $nvimConifig to backup $nvimBackup"
    mv $nvimConifig $nvimBackup
fi

[[ -d $nvimBackup ]] && echo "Backup created at $nvimBackup"
[[ -d $nvimConfig ]] &&
    echo "Error, config file still exists after creating backup $nvimConifig" &&
    exit 1

linkSource=$repoDir
linkTarget=$XDG_CONFIG_HOME/nvim
echo "Creating symbolic link form source ($linkSource) to target ($linkTarget)"
ln -s $linkSource $linkTarget
